# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5f4e9a05e63ccd2056449aa825b5d44fa19e141f4d12a52051c55da381f9e400011f7a5e48d7e7bbb7f9033a8af6c939ff26acef3982e488acafb2f78715909

test:
  secret_key_base: 89140ffe087396a92bb4e2e70bb101d3de0a33f738f40a1593d5587a10f8e3939344b91951f86a49852d3d3b43404bb2f97decdb9b2a4cfceb137310992e89c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
