# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6214fb372fcc0c8f2c24905d4349eb9f1a1129300550f3fb6131166c4f5a6938cb3cec353dfc2fa0347ffa25f26a107340391f1946a7496e47947b7ce27942c

test:
  secret_key_base: 8adb811554687d5f13ebc9c53c9f9ba9dd80a9018e1f91d0ee8b169f2535b23984c52dd66b6713f74add55c4db1f9c4dd2d8a6e5926fb6a95e79331af9e5c595

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
